src/components/DropDown.js

removed unused imports and commented code.

cleaning up unnecessary comments

---

src/actions/index.js
src/components/CardList.js
src/components/DropDown.js
src/components/FieldCard.js
src/index.js
src/store/reducer.js

Have the basic functionality of a store! Yay!

Added the store

---

src/actions/index.js
src/components/CardList.js
src/components/DropDown.js
src/components/FieldCard.js
src/store/reducer.js

- Added redux dropdown update action creator
- Edited reducer for new case
-Overall updating object array upon clicked dropdown selection ***

Updated Redux Store with Dropdown Selection Functionality 

---

src/actions/index.js
src/components/App.js
src/components/CardList.js
src/components/DropDown.js
src/components/FieldCard.js
src/components/FileIn.js
src/store/reducer.js

- Removed redundant functions, import statements, etc.
- Added comments explaining each part of component
- More readable code

Added comments and cleaned up code

---

src/actions/index.js
src/components/CardList.js
src/components/DateDropdown.js
src/store/reducer.js

Using this information in the store, post-selection, we can design function with logic to help decide how to format the given dates in the specified sesar format

Added date formatting widget to store selected format in the redux store

---

src/components/DateDropdown.js
src/components/DropDown.js
src/store/reducer.js

Correctly formatted date added to the store and every case works
- Thoughts on next steps 
- More robust error handling (check if format selected is correct to the best of our abilities)
- Pop up window if no format has been selected
- Functionality where if the user has selected start date in drop and then selects format that it works OR have the dropdown option somehow only selectable if a format has been selected.

correctly formatted date added to the store (works)

---

src/components/DropDown.js

error fixed, may still have a few little bugs will check

---

src/components/App.js
src/components/DropDown.js
src/components/FieldCard.js

When selecting an acceptable date, the ui displays the correct formatting
Does not affect the store negatively
Store displays for example (oldValue: 20171017 value: 2017-10-.....) when a date has been selected, otherwise 'oldValue' is undefined

Formatted date is now viewable in the fieldValue to the left of the dropdown upon selection!

---

src/components/DropDown.js
src/components/FieldCard.js

Now if you click an incorrect option it is not registered in the store or in the dropdown

added dropdown refresh

---

src/components/App.css
src/components/CardList.js
src/components/FieldCard.js

Descriptive header now there, could use some tweaks but at least its there

added descriptive header above fieldCards

---

src/components/DropDown.js
src/components/FieldCard.js

Little more seamless when selecting an incorrect option, the dropdown is refreshed (not perfect, but achieves functionality I was looking for)

more seamless dropdown refresh

---

package-lock.json
package.json
src/actions/index.js
src/components/CardList.js
src/components/DropDown.js
src/components/FieldCard.js
src/components/FormatDropdown.js
src/store/reducer.js

UI updates appropriately 
Redux Store contains the order pair if the pair selection is chosen or if single measurement
Still needed ( handling changing selection on backend)

Added (measurement dropdown dynamic when selecting "size" option)

---

src/components/CardList.js

UPDATE: preview pop-up size selection addition

UPDATE: preview pop-up now shows the size selections (format of js file to be)

---

src/components/App.css
src/components/App.js
src/components/CardList.js
src/components/DateDropdown.js
src/components/DropDown.js

(Update) messy conditionals into functions in the files above

(Update) Code cleanup in App.js & Cardlist.js

---

src/components/CardList.js

Correct Preview Output for Multivalue selections

UPDATED (cleaned up multivalue preview output)

---

src/components/DateDropdown.js
src/components/DropDown.js
src/components/FieldCard.js
src/components/FormatDropdown.js
src/store/reducer.js

Cleaned up code in all components except Dropdown.js
Will do tomorrow....

UPDATE (Code Cleanup)

---

src/components/DropDown.js
src/components/FieldCard.js

Updates the store when "deselecting" a size dropdown first in pair, to also update the store information of the second in pair to show "none" and to update the interface accordingly.

(UPDATE) Fixed Size Selection Bugs

---

package-lock.json
package.json
src/components/CardList.js
src/components/FieldCard.js
src/components/FormatDropdown.js
src/components/MapOutput.js

So far this component has the complete functionality to write single values and multivalues to the file.

ADDED: New component that writes file based on user interaction

---

src/components/FileIn.js
src/components/FormatDropdown.js

- Removed yellow error messages from all components except MapOutput.js

(UPDATE) removed yellow error messages

---

src/components/App.js
src/components/CardList.js
src/components/CenturyDropDown.js
src/components/DateDropdown.js
src/components/DropDown.js
src/components/FieldCard.js
src/index.js

- Clean out the console.logs from debugging sessions this week
- Changed <option selected> to <select defaultValue={'DEFAULT'}> <option value="DEFAULT>
----- This maintains compatibility across form components in React
----- Without this we were getting a red message in the console serving as a warning, so I switched to avoid any bigger issues in the future...
-----NEXT STEPS-----
- Currently looking into Jest, the debugging tool for Unit Testing 
- Accepting and parsing the JS file + Original CSV (Saving Scenario)
- Finishing the MapOutput.js to output the JavaScript file
- FieldValues as Dropdown so the user can select from the n samples to see translation

(UPDATE) Cleaned out console

---

src/components/CardList.js
src/components/FieldCard.js
src/components/FormatDropdown.js
src/components/MapOutput.js

CHANGED: when a size pair value is assigned and the precision unit is an empty string, its store contents is changed to a value of "0"

ADDED: create summation function string output in MapOutput.js

---

src/actions/index.js
src/components/App.js
src/components/CardList.js
src/components/Dialog.js
src/store/reducer.js

- Pop up window felt nicer than a separate tab so we went with this for now.

(ADDED) Fully functional map preview button pop up window.

---

src/actions/index.js
src/components/CardList.js
src/components/DropDown.js
src/components/FieldCard.js
src/store/reducer.js

Bugs:
- Update store on refresh card, (map preview shows collection_start_date after refresh and it shouldn't)
- Size first in pair gets a little wonky when you toggle to an empty string (potential fix is that the array doesn't contain empty strings)

(UPDATE) Toggle functionality works! Bugs to fix..

---

src/components/DropDown.js
src/store/reducer.js

Would cease to be disabled upon next dropdown selection (FIXED)

(UPDATE) Date formatting bug fixed

---

src/components/App.js
src/components/CardList.js
src/components/FieldCard.js

CLEANUP UP:
- App.js
- Cardlist.js (most of) 
** Need to start removing remnants of the size array from the store throughout program
** Pairarray is called numerous times in different components so we need to clean that out

(UPDATE) Code clean up

---

src/components/App.css
src/components/App.js
src/components/CardList.js
src/components/CenturyDropDown.js
src/components/CheckBox.js
src/components/Dialog.js
src/components/DropDown.js
src/components/FieldCard.js
src/components/FileIn.js
src/components/sesarOptions.js
src/store/reducer.js

- Commented out all code referencing (PairArray, SingleMeasure, etc.)
- Significantly simplified components using the FormatDropdown formerly..

(UPDATE) Commented out old "Size" handling

---

src/components/FileIn.js
src/test.js

- Accepts .js file
- Data from let map = { is now correctly parsed and store in the state of fileIn.js
- For now after data is stored, we just return and print to console to avoid any weird UI display, its just not necessary at this point
NEXT STEPS:
- Conditionals to put js file in correct spot based on if it is selected first or second (if necessary)
- Unshift parse js data, to the front of the toggle values arr / normal arr
- Pass back to app, the "size" of the js arr so that those first values displayed to the screen will have a set dropdown and their info will already be in the store

(ADDED) .js file handling for the saved state use case

---

src/components/CardList.js
src/components/FieldCard.js

Now takes .js file with *1 CSV File
REQUIREMENTS: (1CSV), (2CSV), (1JS & 1CSV)
Note:
- Does not automatically format date because the format isn't kept track of in the map output file so the current working version requires you to reenter any dates you selected.

(UPDATE) Fully function .js file functionality 

---

package-lock.json
package.json
src/components/App.js
src/components/App.scss
src/components/CardList.js
src/components/CheckBox.js
src/components/FieldCard.js
src/components/FileIn.js
src/components/MapOutput.js

BEM (BLOCK, ELEMENT, MODIFIER) Methodology
- Methodology for naming class names based off their position in the div so that making edits is easy for the dev to recognize when a change will change another element.

(UPDATE) Switched CSS to SCSS with BEM methodology / code cleanup

---

src/components/CardList.js
src/components/DateDropdown.js
src/components/DropDown.js
src/components/FieldCard.js
src/components/FileIn.js
src/components/sesarOptions.js

- Only thing is upon deselection date, date dropdown should not be disabled..

(UPDATE) Date formatting upon loading in JS Mapping file fully working

---

src/actions/index.js
src/components/CardList.js
src/components/FieldCard.js
src/components/FileIn.js
src/components/MapOutput.js
src/store/reducer.js

- FieldCard: implemented forced metadata field cards to ui and store
- MapOutput: refinement of string creation, specifically output of single values and logic associated with multi value outputs

CHANGES: FieldCard and MapOutput

---

src/components/DropDown.js
src/components/FieldCard.js
src/components/MapOutput.js

-dropdown now properly preserves date format from changing rows and allows user to reset date format by unselecting a SESAR date field.
-mapoutput now dynamically writes date function based on if user chose a date format or not

CHANGES: Dropdown & MapOutput

---

src/components/App.js
src/components/DropDown.js
src/components/FieldCard.js

- One bug to look at is alert window poppin up when selecting two csv's

(BUG FIXED) Input bars when selecting two csv's now fixed

---

src/components/FileIn.js

- Need to reinstitute some specific file handling errors (EASY)
- Just need to adjust logic in 'handleChange()' to slight changes made to mapOutput (Not bad)

(UPDATE) Two Choose File Buttons for mapping and csv files now works

---

src/components/DropDown.js
src/components/sesarOptions.js
src/test.js

Everything currently works as it should.
One fix to make in MapOutput, in regards to remaking the same map. There are issues that need to be dealt with, Robert is on it

(FIX) Bug fixed in dropdown

---

src/components/App.scss
src/components/CardList.js
src/components/DropDown.js
src/components/FieldCard.js
src/components/FileIn.js
src/components/sesarOptions.js
src/util/helper.js

- fixes to count number of csvs for error handling
- fixes to count JS file for error handling
- fixes to dropdown to identify available one to one values
- fixes to dropdown to interact properly with <metadata> assigned cards from JS file load in
- additions to fieldcard to display text on hover over
- addition of helpers.js a utility file for general use functions
- slight refactoring/documentation of fieldcard and dropdown for readability

fixes to enable more metadata_add cards

---

src/components/CardList.js
src/components/CheckBox.js
src/components/DropDown.js
src/components/FieldCard.js
src/components/MapOutput.js
src/components/license.js
src/components/sesarOptions.js
src/store/reducer.js

usercode: no longer allow checkbox
license: is now new seperate file

latest updates to MMM
